baseURL = "https://example.com"
languageCode = "en-us"
title = "Sample Dojo"
theme = "ananke"
defaultContentLanguage = "en"

# Pagination configuration
[pagination]
  pagerSize = 3

# Languages configuration
[languages]
  [languages.en]
    title = "Sample Dojo"
    weight = 1
    contentDir = "content"
    languageName = "English"
    
  # Prepare structure for additional languages (example: Portuguese)
  # [languages.pt]
  #   title = "Dojo de Exemplo"
  #   weight = 2
  #   contentDir = "content"
  #   languageName = "Português"

# Language menu configuration
[menu]
  [[menu.main]]
    identifier = "language"
    name = "Language"
    weight = 100

[params]
  # Site description for meta tags
  description = "A Goju-Ryu Karate dojo website"
  
  # Featured image for social sharing
  featured_image = "/images/logo.png"
  
  # Recent posts on homepage
  recent_posts_number = 3
